FROM ubuntu:24.04


ENV TZ=Europe/Warsaw


# 1. Python w wersji 3.10
RUN add-apt-repository ppa:deadsnakes/ppa -y && \
    apt-get update && apt-get install -y python3.10 python3-pip && \
    rm -rf /var/lib/apt/lists/*

# 2. Java wersja 8 i Kotlin
RUN apt update && apt install -y openjdk-8-jdk curl && \
    curl -sS https://get.sdkman.io | bash && \
    bash -c "source $HOME/.sdkman/bin/sdkman-init.sh && sdk install kotlin" && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
ENV PATH "$JAVA_HOME/bin:$PATH"

# Instalacja Gradle
RUN wget https://services.gradle.org/distributions/gradle-8.5-bin.zip -P /tmp && \
    unzip -d /opt/gradle /tmp/gradle-8.5-bin.zip && \
    rm /tmp/gradle-8.5-bin.zip
    ENV GRADLE_HOME /opt/gradle/gradle-8.5
    ENV PATH "$GRADLE_HOME/bin:$PATH"

WORKDIR /app
COPY . /app

RUN gradle build --no-daemon


CMD gradle run --no-daemon


