name: Build and Deploy Frontend & Backend

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Logowanie do ACR
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CREDENTIALS }}

      # Budowanie i push obrazów
      - name: Build and push backend image
        run: |
          docker build -t $REGISTRY/zad5-backend:latest ./backend
          docker push $REGISTRY/zad5-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t $REGISTRY/zad5-frontend:latest ./frontend
          docker push $REGISTRY/zad5-frontend:latest

